### ISSUE TITLE
USER STORY: Initial setup

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/TDA-SAC#1]
As a **dev** I can **set up the initial project structure** so that **I can get started!**

# Acceptance Criteria

 - Basic project structure set up for a MERN app

# Tasks

- [x] initialise node,js project
```
npm init -y    
```

- [x] install Next.js
```
npx create-next-app@latest .
```

- [x] Remove unwanted boilerplate

- [x] Install required packages
```
npm i mongoose dotenv cors helmet express nodemon http-errors morgan
```

- [x] Add components dir

- [x] Add daisyui

```
npm i -D daisyui@latest
```
add below to tailwind.config.js
```
module.exports = {
  plugins: [require("daisyui")],
}
```

- [x] Add index.js to root

- [x] add below to "scripts" in package.json
```
"start": "nodemon index.js",
```

- [x] Import required libraries etc in index.js
```
const express = require('express');
const app = express();
const mongoose = require('mongoose');
const morgan = require('morgan');
const helmet = require('helmet');
const cors = require('cors');
require('dotenv').config();
const createError = require('http-errors');
const { User } = require('./models/user');
const { v4: uuidv4 } = require('uuid');

const port = 3001;
```

- [x] tell app to use those libraries
```
app.use(express.json());
app.use(morgan);
app.use(helmet());

app.use(
  cors({
    origin: 'http://localhost:3000',
  })
);
```

- [x] Set up server
```
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
```

- [x] Set up Mongodb
add database
- [x] Add connection string to .env
```
MONGODB_URI=mongodb+srv://mjjstockman:**<ADD PASSWORD>**@cluster0.jw4skne.mongodb.net/**<ADD DB NAME**>retryWrites=true&w=majority
```

**Comment by Craigj915** [comment]
Also installed uuidv4, was forgotten in documentation.

**Comment by mjjstockman** [comment]
Nice one! Can u update the docs and add anything to it as u go pretty
please?
