### ISSUE TITLE
USER STORY: calendar

### ISSUE THREAD

**Issue by Craigj915** [mjjstockman/TDA-SAC#16]
As a **dev** I can **create a functional calendar** so that **users can select dates, add events to dates and look for previously added events and edit or remove them**

# Acceptance Criteria

 - Create calendar ui
 - Add event functionality
 - Remove event functionality
 - Edit event functionality
 - Browse through calendar by month or year
 - Colour code events
 - Add descriptions to events

# Tasks

- [x] Ui
- [x] Browse through calendar
- [ ] Add events
- [ ] Edit and remove events
- [ ] Colour code events

# Notes / Resources
