### ISSUE TITLE
USER STORY: database connection

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/TDA-SAC#2]
As a **dev** I can **see  database info on the home page** so that **I can tell the project setup and connection is working**

# Acceptance Criteria

 - I can see user emails that are in the users db on the hompage
 - Acceptance Criteria 2

# Tasks

- [x] Connect to mongoose in index.js
```
mongoose
  .connect(process.env.MONGODB_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
    console.log('Connected to MongoDB');
  })
  .catch((err) => {
    console.log(err);
  });
```

- [x] add models/**<singuarly named model>.js** to root
Add model schema
```
const mongoose = require('mongoose');

const userSchema = mongoose.Schema({
  username: String,
  email: String,
  password: String,
  token: String,
});

module.exports.User = mongoose.model('User', userSchema);
```
- [x] Add data to user database using mongoDB

- [x] Test connection and set up by printing user fields on home page
```
app.get('/', async (_, res, next) => {
  try {
    const users = await User.find();
    const userEmails = users.map((user) => user.email);

    // Render an HTML page with the user emails
    const html = `
      <html>
        <head>
          <title>User Emails</title>
        </head>
        <body>
          <h1>User Emails</h1>
          <ul>
            ${userEmails.map((email) => `<li>${email}</li>`).join('')}
          </ul>
        </body>
      </html>
    `;

    res.send(html);
  } catch (err) {
    return next(createError(500, 'Internal Server Error'));
  }
});
```
