### ISSUE TITLE
USER STORY: user registration

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/TDA-SAC#3]
As a **user** I can **register to the site** so that **I can then sign in**

# Acceptance Criteria

 - There is a clear, easy to use login form on the home page
 - Any errors are shown to me, making it clear where the error is and how to correct it

# Tasks

- [ ] Create registration form with username, email address, repeated email address
- [ ] All fields are required
- [ ] Verify all fields are entered
- [ ] Verify email field contains a valid email
- [ ] Verify emails match
- [ ] Show errors in form to user
- [ ] Add success message
- [ ] Add sent form details to database
