### ISSUE TITLE
USER STORY: User permissions

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/TDA-SAC#45]
As a **Director** I can **make sure all users have the correct permissions so that **everyone can do what they need to and nothing more**

# Acceptance Criteria

 - All roles can access the required routes as stated in the clients Product Backlog
 - Roles cannot access routes outside of their designated role

# Tasks

- [ ] Add permissions to role.js model
### Member of Staff
- [ ] canRequestLeave: Ability to submit annual leave requests.
- [ ] canAddSickNote: Ability to add doctors' notes or other documentation to logged sickness.
- [ ] canSeeRemainingLeave: Ability to see how much leave is remaining.
- [ ] canSeeLeaveStatus: Ability to see if leave requests have been approved or not.
- [ ] canSeeTeamLeaveCalendar: Ability to see their team's booked leave days on a calendar.
- [ ] canSeeCourseCalendar: Ability to see course delivery displayed on a calendar.
- [ ] canSeeInstructorSchedule: Ability to see who is delivering courses at a given time.
- [ ] canBeNotifiedNewCourse: Ability to receive notifications when booked on a new course.
- [ ] canSeeDashboardSummary: Ability to see a handy summary of key information when logging in.

### Instructor
- [ ] canSeeCourseSchedule: Ability to see when courses are scheduled.

### Manager
- [ ] canSeeTeamLeaveRequests: Ability to see new leave requests from their team.
- [ ] canDeclineLeaveRequest: Ability to decline a leave request.
- [ ] canSeeTeamLeaveReport: Ability to see a report showing numbers of leave days taken by their team (broken down by year).
- [ ] canSeeTeamLeaveCalendar: Ability to see their team's booked leave days on a calendar.
- [ ] canSeeTeamSickReport: Ability to see a report showing numbers of sick days taken by their team (broken down by year).
- [ ] canSeeTeamSickDetails: Ability to see details of sickness absence and attachments for their team.
- [ ] canAddNewStaff: Ability to add new members of staff.

### Director
- [ ] canSeeOrganizationLeaveReport: Ability to see a report showing numbers of leave days taken by all staff (broken down by year).
- [ ] canSeeOrganizationLeaveCalendar: Ability to see all staff booked leave days on a calendar.
- [ ] canSeeOrganizationSickReport: Ability to see a report showing numbers of sick days taken by all staff (broken down by year).

### Course Manager
- [ ] canAddNewCourses: Ability to add new courses to the schedule.

### Marketing/Admissions Staff
- [ ] canSeeCohortStartDates: Ability to see start dates for next cohorts for all courses.

### All Users
- [ ] canSeeDashboardSummary: Ability to see a handy summary of key information when logging in.
- [ ] canReceiveNotifications: Ability to receive notifications for relevant events (e.g., new course bookings, leave request status changes).

- [ ] Add middleware to check permissions
- [ ] Use middleware in routes

# Notes / Resources
How add permission:
```
{
  "_id": ObjectId("user_id"),
  "username": "john_doe",
  "email": "john@example.com",
  "role": "member_of_staff",
  "permissions": ["canRequestLeave", "canAddSickNote", ...]
}
```

How check permission:
```
// middleware/permissionMiddleware.js

const checkPermission = (requiredPermission) => (req, res, next) => {
  if (req.user && req.user.permissions.includes(requiredPermission)) {
    next();
  } else {
    res.status(403).json({ error: "Insufficient permissions" });
  }
};

module.exports = checkPermission;

```

How use middleware in routes:
```
// routes/leaveRoutes.js

const checkPermission = require('../middleware/permissionMiddleware');

// Example usage for a route that requires 'canRequestLeave' permission
router.post('/request-leave', checkPermission('canRequestLeave'), (req, res) => {
  // Handle the leave request
});


```
